name: smartsacco
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:

  flutter:
    sdk: flutter

  # Firebase packages
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  app_links: 6.4.0

  # Utility packages
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  http: ^1.4.0
  csv: ^6.0.0

  # UI packages
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  syncfusion_flutter_datepicker: ^30.1.39
  slide_to_confirm: ^1.1.0
  fl_chart: ^1.0.0

  # Audio and Speech
  flutter_tts: ^4.2.3
  speech_to_text: ^7.1.0


  # Others
  logging: ^1.3.0
  intl: 0.20.2
  universal_html: ^2.2.4
  share_plus: ^11.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
